Version tab showing
Johngtka/Biomagnethick-app pull request #38
Opened 2023-05-08 14:09 UTC by Johngtka

2023-05-09 11:18 UTC, macrog commented
at this point we have that

| prod | dev | 
| --- | --- |
| ![image](https://github.com/Johngtka/Biomagnethick-app/assets/11686968/f55fc820-6cbd-47f7-b693-4f576b7416ec) | ![image](https://github.com/Johngtka/Biomagnethick-app/assets/11686968/e7190257-e6c7-48e4-84d8-7df5b0310fcb) |

and what we want is something like this:
![image](https://github.com/Johngtka/Biomagnethick-app/assets/11686968/862207b6-06e6-4906-816b-219b02effc40)

please add missing things, and style it so it looks more less like on above design

2023-05-09 11:21 UTC, macrog commented on src/app/about/about.component.ts
> +import { environment } from '../../environments/environment';
we have 3 files in environment folder:
![image](https://github.com/Johngtka/Biomagnethick-app/assets/11686968/c526d762-8e61-417e-bcfa-b1080094374e)

always use `environment .ts` in any import!

2023-05-09 11:21 UTC, macrog commented on src/app/services/patient-service.ts
> +import { environment } from '../../environments/environment';
we have 3 files in environment folder:
![image](https://github.com/Johngtka/Biomagnethick-app/assets/11686968/c526d762-8e61-417e-bcfa-b1080094374e)

always use `environment .ts` in any import!

2023-05-09 11:22 UTC, macrog commented on src/app/services/store.service.ts
> +import { environment } from '../../environments/environment';
we have 3 files in environment folder:
![image](https://github.com/Johngtka/Biomagnethick-app/assets/11686968/c526d762-8e61-417e-bcfa-b1080094374e)

always use `environment .ts` in any import!

2023-05-09 11:22 UTC, macrog commented on src/app/services/visit.service.ts
> +import { environment } from '../../environments/environment';
we have 3 files in environment folder:
![image](https://github.com/Johngtka/Biomagnethick-app/assets/11686968/c526d762-8e61-417e-bcfa-b1080094374e)

always use `environment.ts` in any import!

2023-05-09 21:02 UTC, Johngtka commented
S&M commit proposal:
`feat: project version improvement - displaying info (#)`

2023-05-11 08:26 UTC, macrog requested changes

2023-05-11 08:26 UTC, macrog commented on src/app/about/about.component.ts
> +    Title = environment.TITLE;
why `Title` with uppercase? it should be `title`

2023-05-11 08:26 UTC, macrog commented on src/app/about/about.component.ts
> +import { environment } from '../../environments/environment';
organize imports, add empty line in between different sections of imports

2023-05-11 08:58 UTC, macrog commented
Show the same icon that we use in the about page as a `favicon` ❗

2023-05-11 09:07 UTC, Johngtka commented
> Show the same icon that we use in the about page as a `favicon` ❗

like this
![obraz](https://github.com/Johngtka/Biomagnethick-app/assets/79154804/13786241-d39d-4765-a0ab-619c94cd7c6b)

2023-05-11 09:50 UTC, macrog commented on src/app/about/about.component.html
> +                type="image/x-icon"
what is this for?

2023-05-11 16:12 UTC, macrog approved these changes
👍

2023-05-12 10:13 UTC, merged